---
dependencies:
  - role: apache
  - role: ctl-ssl
    name: "{{ apache_auth.vhost_name }}"
    ssl_cert: "{{ apache_auth.ssl.cert }}"
    ssl_key: "{{ apache_auth.ssl.key }}"
    ssl_ca_cert: "{{ apache_auth.ssl.ca_cert}}"
    ssl_intermediate: "{{ apache_auth.ssl.intermediate }}"
    when: apache_auth.ssl.enabled|bool
  - role: sensu-check
