---
apt_mirror:
  apache:
    http_redirect: False
    servername: mirror01.local
    serveraliases:
      - mirror01
    port: 80
    ip: '*'
    ssl:
      enabled: False
      port: 443
      ip: '*'
      name: cuttle
      cert: ~
      key: ~
      intermediate: ~
  firewall:
    - port: 80
      protocol: tcp
      src: 0.0.0.0/0
    - port: 443
      protocol: tcp
      src: 0.0.0.0/0
  path: /opt/apt-mirror
  htpasswd_location: /opt/apt-mirror/etc
  debmirror:
    repositories: {}
    distros: {}
  logs:
    # See logging-config/defaults/main.yml for filebeat vs. logstash-forwarder example
    - paths:
        - /var/log/apache2/apt_mirror-access.log
      fields:
        tags: mirror,apache_access
    - paths:
        - /var/log/apache2/apt_mirror-error.log
      fields:
        tags: mirror,apache_error
  logging:
    forwarder: filebeat
